@extends('pms.backend.layouts.master-layout')
@section('title', config('app.name', 'laravel'). ' | '.$title)
@section('page-css')

@endsection
@section('main-content')
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="{{  route('pms.dashboard') }}">{{ __('Home') }}</a>
                </li>
                <li>
                    <a href="#">PMS</a>
                </li>
                <li class="active">{{__($title)}}</li>
                <li class="top-nav-btn">
                    <a href="javascript:history.back()" class="btn btn-sm btn-warning text-white" data-toggle="tooltip" title="Back" > <i class="las la-chevron-left"></i>Back</a>
                </li>
            </ul><!-- /.breadcrumb -->
        </div>

        <div class="page-content">
            <div class="">
                <div class="panel panel-body">

                    {!! Form::open(['route' => 'pms.quotation.quotations.cs.compare.approved',  'files'=> false, 'id'=>'', 'class' => '']) !!}
                    <div class="row">
                        @foreach($quotations as $q_key => $quotation)
                        <?php 
                        $TS = number_format($quotation->relSuppliers->SupplierRatings->sum('total_score'),2);
                        $TC = $quotation->relSuppliers->SupplierRatings->count();
                        $totalScore = isset($TS)?$TS:0;
                        $totalCount = isset($TC)?$TC:0;
                    ?>

                    <div class="col-md-<?=$quotations->count()>1?6:12?>">
                        <div class="panel panel-info">
                         
                            <div class="col-lg-12 invoiceBody">
                                <div class="invoice-details mt25 row">
                                    
                                    <div class="well col-6">
                                        <ul class="list-unstyled mb0">
                                            <li>

                                                <div class="ratings">
                                                    <a href="{{route('pms.supplier.profile',$quotation->relSuppliers->id)}}" target="_blank"><span>Rating:</span></a> {!!ratingGenerate($totalScore,$totalCount)!!}
                                                </div>
                                                <h5 class="review-count"></h5>
                                            </li>
                                            <li><strong>{{__('Supplier')}} :</strong> {{$quotation->relSuppliers->name}}</li>
                                            <li><strong>{{__('Email')}} :</strong> {{$quotation->relSuppliers->email}}</li>
                                            <li><strong>{{__('Phone')}} :</strong> {{$quotation->relSuppliers->phone}}</li>
                                            <li><strong>{{__('Payment Term')}} :</strong> {{isset($quotation->relSupplierPaymentTerm->relPaymentTerm->term)?$quotation->relSupplierPaymentTerm->relPaymentTerm->term:''}}</li>

                                            
                                        </ul>
                                    </div>
                                    <div class="col-6">
                                        <ul class="list-unstyled mb0 pull-right">
                                            <li><strong>{{__('Date')}} :</strong> {{date('d-m-Y',strtotime($quotation->quotation_date))}}</li>
                                            <li><strong>{{__('Reference No')}}:</strong> {{$quotation->reference_no}}</li>
                                            <li><strong>{{__('RFP No')}}:</strong> {{$quotation->relRequestProposal->reference_no}}</li>
                                            <li><strong>{{__('Generated By')}}:</strong> {{isset($quotation->relRequestProposal->createdBy->name)?$quotation->relRequestProposal->createdBy->name:''}}</li>

                                            <li>
                                                <div class="form-check">
                                                  <input class="form-check-input" type="radio" name="quotation_id" id="is_approved_{{$quotation->id}}" value="{{$quotation->id}}" {{ $q_key == 0 ? 'checked' : ''  }} style="display: {{ $quotations->count() > 1 ? 'block' : 'none' }}" required>
                                                  <input type="hidden" name="request_proposal_id" value="{{$quotation->request_proposal_id}}">
                                                  <label class="form-check-label" for="is_approved_{{$quotation->id}}" style="margin-left: {{ $quotations->count() > 1 ? '0px' : '-20px' }}">
                                                    <strong>Approval</strong>
                                                  </label>
                                                </div>
                                            </li>
                                    </ul>
                                </div>
                                
                            </div>
                        </div>
                        <div class="table-responsive">

                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Sl No.</th>
                                        <th>Category</th>
                                        <th>Product</th>
                                        <th>Unit</th>
                                        <th>Unit Price</th>
                                        <th>Qty</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($quotation->relQuotationItems as $key=>$item)
                                    <tr>
                                        <td>{{$key+1}}</td>
                                        <td>{{$item->relProduct->category->name}}</td>
                                        <td>{{$item->relProduct->name}} ({{getProductAttributes($item->relProduct->id)}})</td>
                                        <td>{{$item->relProduct->productUnit->unit_name}}</td>
                                        <td>{{$item->unit_price}}</td>
                                        <td>{{$item->qty}}</td>
                                        <td>{{number_format($item->total_price,2)}}</td>
                                    </tr>
                                    @endforeach

                                    <tr>
                                        <td colspan="4" class="text-right">Total</td>
                                        <td colspan="">{{number_format($quotation->relQuotationItems->sum('unit_price'),2)}}</td>
                                        <td colspan="">{{number_format($quotation->relQuotationItems->sum('qty'),2)}}</td>
                                        <td colspan="">{{number_format($quotation->relQuotationItems->sum('total_price'),2)}}</td>
                                    </tr>

                                    <tr>
                                        <td colspan="6" class="text-right">(-) Discount</td>
                                        <td>{{number_format($quotation->discount,2)}}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="6" class="text-right">(+) Vat </td>
                                        <td>{{number_format($quotation->vat,2)}}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="6" class="text-right"><strong>Total Amount</strong></td>
                                        <td><strong>{{number_format($quotation->gross_price,2)}}</strong></td>
                                    </tr>
                                    
                                   <tr>
                                        <td>
                                            <strong>{{__('Notes')}}</strong>
                                        </td>
                                        <td colspan="6">
                                           {{$quotation->note}}
                                       </td>
                                   </tr>
                                   
                               </tbody>
                           </table>
                           
                       </div>


                       <div class="form-group">
                        <label for="remarks"><strong>Remarks</strong>:</label>

                        <textarea class="form-control" name="remarks" rows="1" id="remarks" placeholder="Remarks">{!! $quotation->remarks?$quotation->remarks:'' !!}</textarea>

                    </div>

                </div>
            </div>
            @endforeach
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="submit" class="btn btn-success">Submit</button>
            
        </div>

        {!! Form::close() !!}
    </div>
</div>
</div>
</div>
</div>

@endsection