 @if(isset($quotations))


<div class="col-md-12>">
    <div class="panel panel-info">

        <div class="col-lg-12 invoiceBody">
            <div class="invoice-details mt25 row">
               
            <div class="well col-6">
                <ul class="list-unstyled mb0">
                    <li>
                        <?php 
                        $TS = number_format($quotations->relSuppliers->SupplierRatings->sum('total_score'),2);
                        $TC = $quotations->relSuppliers->SupplierRatings->count();

                        $totalScore = isset($TS)?$TS:0;
                        $totalCount = isset($TC)?$TC:0;
                    ?>

                        <div class="ratings">
                            <a href="{{route('pms.supplier.profile',$quotations->relSuppliers->id)}}" target="_blank"><span>Rating:</span></a> {!!ratingGenerate($totalScore,$totalCount)!!}
                        </div>
                        <h5 class="review-count"></h5>
                    </li>
                    <li><strong>{{__('Supplier')}} :</strong> {{$quotations->relSuppliers->name}}</li>
                    <li><strong>{{__('Email')}} :</strong> {{$quotations->relSuppliers->email}}</li>
                    <li><strong>{{__('Phone')}} :</strong> {{$quotations->relSuppliers->phone}}</li>

                    @if(isset($quotations->relSupplierPaymentTerm->relPaymentTerm->term))
                    <li><strong>{{__('Payment Term')}} :</strong> {{isset($quotations->relSupplierPaymentTerm->relPaymentTerm->term)?$quotations->relSupplierPaymentTerm->relPaymentTerm->term:''}}</li>
                    
                 </tr>
                 @endif
                    
                </ul>
            </div>
             <div class="col-6">
                <ul class="list-unstyled mb0 pull-right">
                    <li><strong>{{__('Date')}} :</strong> {{date('d-m-Y',strtotime($quotations->quotation_date))}}</li>
                    <li><strong>{{__('Reference No')}}:</strong> {{$quotations->reference_no}}</li>
                    <li><strong>{{__('RFP No')}}:</strong> {{$quotations->relRequestProposal->reference_no}}</li>
                    <li><strong>{{__('Generated By')}}:</strong> {{$quotations->relRequestProposal->createdBy->name}}</li>

                    
            </ul>
            </div>
        
    </div>
</div>
<div class="table-responsive">

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Sl No.</th>
                <th>Category</th>
                <th>Product</th>
                <th>Unit</th>
                <th>Unit Price</th>
                <th>Qty</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>


            @foreach($quotations->relQuotationItems as $key=>$item)
            <tr>
                <td>{{$key+1}}</td>
                <td>{{$item->relProduct->category->name}}</td>
                <td>{{$item->relProduct->name}} ({{ getProductAttributes($item->product_id) }})</td>
                <td>{{$item->relProduct->productUnit->unit_name}}</td>
                <td>{{$item->unit_price}}</td>
                <td>{{$item->qty}}</td>
                <td>{{number_format($item->total_price,2)}}</td>
            </tr>
            @endforeach
            
            <tr>
                <td colspan="4" class="text-right">Total</td>
                <td colspan="">{{number_format($quotations->relQuotationItems->sum('unit_price'),2)}}</td>
                <td colspan="">{{number_format($quotations->relQuotationItems->sum('qty'),0)}}</td>
                <td colspan="">{{number_format($quotations->relQuotationItems->sum('total_price'),2)}}</td>
            </tr>

            <tr>
                <td colspan="6" class="text-right">(-) Discount</td>
                <td>{{number_format($quotations->discount,2)}}</td>
            </tr>
            <tr>
                <td colspan="6" class="text-right">(+) Vat </td>
                <td>{{number_format($quotations->vat,2)}}</td>
            </tr>
            <tr>
                <td colspan="6" class="text-right">Total Amount</td>
                <td>{{number_format($quotations->gross_price,2)}}</td>
            </tr>
            
            @if(isset($quotations->remarks))
            <tr>
                <td class="text-left">Notes</td>
                <td  colspan="6">{{$quotations->remarks}}</td>
            </tr>
            @endif

            @if(isset($quotations->note))
            <tr>
                <td class="text-left">Notes</td>
                <td class="text-left" colspan="6">{{$quotations->note}}</td>
            </tr>
            @endif

        </tbody>
    </table>
</div>
</div>
</div>
@endif