 <?php if(isset($quotations)): ?>


<div class="col-md-12>">
    <div class="panel panel-info">

        <div class="col-lg-12 invoiceBody">
            <div class="invoice-details mt25 row">
               
            <div class="well col-6">
                <ul class="list-unstyled mb0">
                    <li>
                        <?php 
                        $TS = number_format($quotations->relSuppliers->SupplierRatings->sum('total_score'),2);
                        $TC = $quotations->relSuppliers->SupplierRatings->count();

                        $totalScore = isset($TS)?$TS:0;
                        $totalCount = isset($TC)?$TC:0;
                    ?>

                        <div class="ratings">
                            <a href="<?php echo e(route('pms.supplier.profile',$quotations->relSuppliers->id)); ?>" target="_blank"><span>Rating:</span></a> <?php echo ratingGenerate($totalScore,$totalCount); ?>

                        </div>
                        <h5 class="review-count"></h5>
                    </li>
                    <li><strong><?php echo e(__('Supplier')); ?> :</strong> <?php echo e($quotations->relSuppliers->name); ?></li>
                    <li><strong><?php echo e(__('Email')); ?> :</strong> <?php echo e($quotations->relSuppliers->email); ?></li>
                    <li><strong><?php echo e(__('Phone')); ?> :</strong> <?php echo e($quotations->relSuppliers->phone); ?></li>

                    <?php if(isset($quotations->relSupplierPaymentTerm->relPaymentTerm->term)): ?>
                    <li><strong><?php echo e(__('Payment Term')); ?> :</strong> <?php echo e(isset($quotations->relSupplierPaymentTerm->relPaymentTerm->term)?$quotations->relSupplierPaymentTerm->relPaymentTerm->term:''); ?></li>
                    
                 </tr>
                 <?php endif; ?>
                    
                </ul>
            </div>
             <div class="col-6">
                <ul class="list-unstyled mb0 pull-right">
                    <li><strong><?php echo e(__('Date')); ?> :</strong> <?php echo e(date('d-m-Y',strtotime($quotations->quotation_date))); ?></li>
                    <li><strong><?php echo e(__('Reference No')); ?>:</strong> <?php echo e($quotations->reference_no); ?></li>
                    <li><strong><?php echo e(__('RFP No')); ?>:</strong> <?php echo e($quotations->relRequestProposal->reference_no); ?></li>
                    <li><strong><?php echo e(__('Generated By')); ?>:</strong> <?php echo e($quotations->relRequestProposal->createdBy->name); ?></li>

                    
            </ul>
            </div>
        
    </div>
</div>
<div class="table-responsive">

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Sl No.</th>
                <th>Category</th>
                <th>Product</th>
                <th>Unit</th>
                <th>Unit Price</th>
                <th>Qty</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>


            <?php $__currentLoopData = $quotations->relQuotationItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($key+1); ?></td>
                <td><?php echo e($item->relProduct->category->name); ?></td>
                <td><?php echo e($item->relProduct->name); ?> (<?php echo e(getProductAttributes($item->product_id)); ?>)</td>
                <td><?php echo e($item->relProduct->productUnit->unit_name); ?></td>
                <td><?php echo e($item->unit_price); ?></td>
                <td><?php echo e($item->qty); ?></td>
                <td><?php echo e(number_format($item->total_price,2)); ?></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            
            <tr>
                <td colspan="4" class="text-right">Total</td>
                <td colspan=""><?php echo e(number_format($quotations->relQuotationItems->sum('unit_price'),2)); ?></td>
                <td colspan=""><?php echo e(number_format($quotations->relQuotationItems->sum('qty'),0)); ?></td>
                <td colspan=""><?php echo e(number_format($quotations->relQuotationItems->sum('total_price'),2)); ?></td>
            </tr>

            <tr>
                <td colspan="6" class="text-right">(-) Discount</td>
                <td><?php echo e(number_format($quotations->discount,2)); ?></td>
            </tr>
            <tr>
                <td colspan="6" class="text-right">(+) Vat </td>
                <td><?php echo e(number_format($quotations->vat,2)); ?></td>
            </tr>
            <tr>
                <td colspan="6" class="text-right">Total Amount</td>
                <td><?php echo e(number_format($quotations->gross_price,2)); ?></td>
            </tr>
            
            <?php if(isset($quotations->remarks)): ?>
            <tr>
                <td class="text-left">Notes</td>
                <td  colspan="6"><?php echo e($quotations->remarks); ?></td>
            </tr>
            <?php endif; ?>

            <?php if(isset($quotations->note)): ?>
            <tr>
                <td class="text-left">Notes</td>
                <td class="text-left" colspan="6"><?php echo e($quotations->note); ?></td>
            </tr>
            <?php endif; ?>

        </tbody>
    </table>
</div>
</div>
</div>
<?php endif; ?><?php /**PATH D:\xampp\htdocs\procurement.zbridea.com\resources\views/pms/backend/pages/quotation/item-show.blade.php ENDPATH**/ ?>