
<?php $__env->startSection('title', config('app.name', 'laravel'). ' | '.$title); ?>
<?php $__env->startSection('page-css'); ?>

<?php $__env->stopSection(); ?>
<?php $__env->startSection('main-content'); ?>
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="<?php echo e(route('pms.dashboard')); ?>"><?php echo e(__('Home')); ?></a>
                </li>
                <li>
                    <a href="#">PMS</a>
                </li>
                <li class="active"><?php echo e(__($title)); ?></li>
                <li class="top-nav-btn">
                    <a href="javascript:history.back()" class="btn btn-sm btn-warning text-white" data-toggle="tooltip" title="Back" > <i class="las la-chevron-left"></i>Back</a>
                </li>
            </ul><!-- /.breadcrumb -->
        </div>

        <div class="page-content">
            <div class="">
                <div class="panel panel-body">

                    <?php echo Form::open(['route' => 'pms.quotation.quotations.cs.compare.approved',  'files'=> false, 'id'=>'', 'class' => '']); ?>

                    <div class="row">
                        <?php $__currentLoopData = $quotations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $q_key => $quotation): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                        <?php 
                        $TS = number_format($quotation->relSuppliers->SupplierRatings->sum('total_score'),2);
                        $TC = $quotation->relSuppliers->SupplierRatings->count();
                        $totalScore = isset($TS)?$TS:0;
                        $totalCount = isset($TC)?$TC:0;
                    ?>

                    <div class="col-md-<?=$quotations->count()>1?6:12?>">
                        <div class="panel panel-info">
                         
                            <div class="col-lg-12 invoiceBody">
                                <div class="invoice-details mt25 row">
                                    
                                    <div class="well col-6">
                                        <ul class="list-unstyled mb0">
                                            <li>

                                                <div class="ratings">
                                                    <a href="<?php echo e(route('pms.supplier.profile',$quotation->relSuppliers->id)); ?>" target="_blank"><span>Rating:</span></a> <?php echo ratingGenerate($totalScore,$totalCount); ?>

                                                </div>
                                                <h5 class="review-count"></h5>
                                            </li>
                                            <li><strong><?php echo e(__('Supplier')); ?> :</strong> <?php echo e($quotation->relSuppliers->name); ?></li>
                                            <li><strong><?php echo e(__('Email')); ?> :</strong> <?php echo e($quotation->relSuppliers->email); ?></li>
                                            <li><strong><?php echo e(__('Phone')); ?> :</strong> <?php echo e($quotation->relSuppliers->phone); ?></li>
                                            <li><strong><?php echo e(__('Payment Term')); ?> :</strong> <?php echo e(isset($quotation->relSupplierPaymentTerm->relPaymentTerm->term)?$quotation->relSupplierPaymentTerm->relPaymentTerm->term:''); ?></li>

                                            
                                        </ul>
                                    </div>
                                    <div class="col-6">
                                        <ul class="list-unstyled mb0 pull-right">
                                            <li><strong><?php echo e(__('Date')); ?> :</strong> <?php echo e(date('d-m-Y',strtotime($quotation->quotation_date))); ?></li>
                                            <li><strong><?php echo e(__('Reference No')); ?>:</strong> <?php echo e($quotation->reference_no); ?></li>
                                            <li><strong><?php echo e(__('RFP No')); ?>:</strong> <?php echo e($quotation->relRequestProposal->reference_no); ?></li>
                                            <li><strong><?php echo e(__('Generated By')); ?>:</strong> <?php echo e(isset($quotation->relRequestProposal->createdBy->name)?$quotation->relRequestProposal->createdBy->name:''); ?></li>

                                            <li>
                                                <div class="form-check">
                                                  <input class="form-check-input" type="radio" name="quotation_id" id="is_approved_<?php echo e($quotation->id); ?>" value="<?php echo e($quotation->id); ?>" <?php echo e($q_key == 0 ? 'checked' : ''); ?> style="display: <?php echo e($quotations->count() > 1 ? 'block' : 'none'); ?>" required>
                                                  <input type="hidden" name="request_proposal_id" value="<?php echo e($quotation->request_proposal_id); ?>">
                                                  <label class="form-check-label" for="is_approved_<?php echo e($quotation->id); ?>" style="margin-left: <?php echo e($quotations->count() > 1 ? '0px' : '-20px'); ?>">
                                                    <strong>Approval</strong>
                                                  </label>
                                                </div>
                                            </li>
                                    </ul>
                                </div>
                                
                            </div>
                        </div>
                        <div class="table-responsive">

                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Sl No.</th>
                                        <th>Category</th>
                                        <th>Product</th>
                                        <th>Unit</th>
                                        <th>Unit Price</th>
                                        <th>Qty</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $__currentLoopData = $quotation->relQuotationItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                    <tr>
                                        <td><?php echo e($key+1); ?></td>
                                        <td><?php echo e($item->relProduct->category->name); ?></td>
                                        <td><?php echo e($item->relProduct->name); ?> (<?php echo e(getProductAttributes($item->relProduct->id)); ?>)</td>
                                        <td><?php echo e($item->relProduct->productUnit->unit_name); ?></td>
                                        <td><?php echo e($item->unit_price); ?></td>
                                        <td><?php echo e($item->qty); ?></td>
                                        <td><?php echo e(number_format($item->total_price,2)); ?></td>
                                    </tr>
                                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>

                                    <tr>
                                        <td colspan="4" class="text-right">Total</td>
                                        <td colspan=""><?php echo e(number_format($quotation->relQuotationItems->sum('unit_price'),2)); ?></td>
                                        <td colspan=""><?php echo e(number_format($quotation->relQuotationItems->sum('qty'),2)); ?></td>
                                        <td colspan=""><?php echo e(number_format($quotation->relQuotationItems->sum('total_price'),2)); ?></td>
                                    </tr>

                                    <tr>
                                        <td colspan="6" class="text-right">(-) Discount</td>
                                        <td><?php echo e(number_format($quotation->discount,2)); ?></td>
                                    </tr>
                                    <tr>
                                        <td colspan="6" class="text-right">(+) Vat </td>
                                        <td><?php echo e(number_format($quotation->vat,2)); ?></td>
                                    </tr>
                                    <tr>
                                        <td colspan="6" class="text-right"><strong>Total Amount</strong></td>
                                        <td><strong><?php echo e(number_format($quotation->gross_price,2)); ?></strong></td>
                                    </tr>
                                    
                                   <tr>
                                        <td>
                                            <strong><?php echo e(__('Notes')); ?></strong>
                                        </td>
                                        <td colspan="6">
                                           <?php echo e($quotation->note); ?>

                                       </td>
                                   </tr>
                                   
                               </tbody>
                           </table>
                           
                       </div>


                       <div class="form-group">
                        <label for="remarks"><strong>Remarks</strong>:</label>

                        <textarea class="form-control" name="remarks" rows="1" id="remarks" placeholder="Remarks"><?php echo $quotation->remarks?$quotation->remarks:''; ?></textarea>

                    </div>

                </div>
            </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="submit" class="btn btn-success">Submit</button>
            
        </div>

        <?php echo Form::close(); ?>

    </div>
</div>
</div>
</div>
</div>

<?php $__env->stopSection(); ?>
<?php echo $__env->make('pms.backend.layouts.master-layout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH D:\xampp\htdocs\procurement.zbridea.com\resources\views/pms/backend/pages/quotation/_compare_view_grid.blade.php ENDPATH**/ ?>